---
- name: Create authorised user accounts
  user:
    name: "{{ item }}"
    groups: sudo
    append: yes
    state: present
    shell: /bin/bash
    system: no
    createhome: yes
  with_items: "{{ authorized_users }}"

- name: "Add authorized keys"
  authorized_key:
    user: "{{ item }}"
    key: "{{ lookup('file', 'files/'+ item + '.key.pub') }}"
  with_items: "{{ authorized_users }}"

- name: allow authorised users to use sudo without needing a password
  lineinfile:
    dest: /etc/sudoers
    line: "{{ item }} ALL=(ALL) NOPASSWD: ALL"
    validate: 'visudo -cf %s'
  with_items: "{{ authorized_users }}"

        