---
- name: Render qnap password to variable
  set_fact:
    storage_qnap_password_enc: "{{ vars.storage_qnap_password | b64encode }}"

- debug:
    msg: "{{ storage_qnap_password_enc }}"

- name: Install qnap storage provisioner
  become: yes
  become_user: kube
  become_method: sudo
  kubernetes.core.k8s:
    state: present
    template: qnap-storage-provisioner.yml.j2
    validate:
      fail_on_error: yes

- name: Install local storage provisioner
  become: yes
  become_user: kube
  become_method: sudo
  kubernetes.core.k8s:
    state: present
    template: local-storage-class.yml.j2
    validate:
      fail_on_error: yes

- name: Install MySQL
  include_tasks: "mysql.yml"

- name: Install Memcached
  include_tasks: "memcached.yml"